### PR TITLE
450

### PR DESCRIPTION
**Pull request by nicklester**
Hi @e-orz  - not sure if we want to do this, but Yan suggested this is the best metric.

### CODE REVIEW

**Comment by nicklester** [comment]
Hi Yaakov - do you have time to review this?

**Comment by e-orz** [comment]
What I don't like about it is the fact that in case there are no new updates the rate will drop to 0 (give the feeling of a stuck system) even though the system is still running ok.
It's the same issue with current one minute rate...

Maybe you can add both metrics... I really don't know.

**Comment by nicklester** [comment]
I don't disagree, but I know @yanpom was very keen for it to work this way.

**Comment by nicklester** [comment]
Maybe as part of the dashboard improvements  (#392) we could think about adding the old metric in again so that we track both? Don't know what else to do really given @yanpom  is not around at the moment

**Comment by nicklester** [comment]
I'll put the old metric back for next release as discussed. Will add to the dashboard enhancements ticket #392

**Pull request merged**
